### ISSUE TITLE
Error 520 when behind nginx reverse proxy

### ISSUE THREAD

**Issue by leon1995** [xwiki-labs/cryptpad-docker#28]
Hi,

I always get an error when visiting my cryptpad domain behind an nginx reverse proxy: `520: Web server is returning an unknown error`.
My docker-compose.yml:
```
version: '3.8'

services:
  cryptpad:
    image: "promasu/cryptpad:nginx"
    hostname: cryptpad
    environment:
      - CPAD_TRUSTED_PROXY=(ip of my reverse proxy)/8
      - CPAD_REALIP_HEADER=X-Forwarded-For
      - CPAD_REALIP_RECURSIVE=on
      - CPAD_MAIN_DOMAIN=cryptpad.mydomain.xyz
      - CPAD_SANDBOX_DOMAIN=sandbox.mydomain.xyz
    volumes:
      - ./data/blob:/cryptpad/blob
      - ./data/block:/cryptpad/block
      - ./data/customize:/cryptpad/customize
      - ./data/data:/cryptpad/data
      - ./data/files:/cryptpad/datastore
      - ./data/config.js:/cryptpad/config/config.js
      - ./data/logs:/cryptpad/data/logs
      - ./data/archive:/cryptpad/data/archive
    ports:
      - "80:80"
```
I copied the default config from cryptpad and changed
```
httpUnsafeOrigin: 'https://cryptpad.mydomain.xyz',
httpSafeOrigin: "https://sandbox.mydomain.xyz",
```

In my reverse proxy I forwarded both domains to the ip address of my cryptpad instance on port 80.

I hope you can help me :)
